version: '3.3'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.5.4
    ports:
      - "9200:9200"
      - "9300:9300"
    configs:
      - source: elastic_config
        target: /usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - /data/elk:/usr/share/elasticsearch/data
      - /etc/localtime:/etc/localtime

  logstash:
    image: docker.elastic.co/logstash/logstash-oss:6.5.4
    ports:
      - "5044:5044"
      - "9600:9600"
    configs:
      #ogirinal
      - source: logstash_config
        target: /usr/share/logstash/config/logstash.yml
      - source: logstash_pipeline
        target: /usr/share/logstash/pipeline/logstash.conf
      ###fim original
      - source: 01-input.conf
        target: /etc/logstash/conf.d/01-input.conf
      - source: 11-pfsense.conf
        target: /etc/logstash/conf.d/11-pfsense.conf
      - source: 10-syslog.conf
        target: /etc/logstash/conf.d/10.syslog.conf
      - source: 30-outputs.conf
        target: /etc/logstash/conf.d/30-outputs.conf
      - source: pfsense_2_4_2.grok
        target: /etc/logstash/piperline/pfsense_2_4_2.grok
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    volumes:
      - /etc/localtime:/etc/localtime
    deploy:
      mode: replicated
      replicas: 1

  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.5.4
    ports:
      - "5601:5601"
    configs:
      - source: kibana_config
        target: /usr/share/kibana/config/kibana.yml
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 1

configs:
##elasticsearsh configs
  elastic_config:
    file: ./elasticsearch/config/elasticsearch.yml
#Logstash configs
  logstash_config:
    file: ./logstash/config/logstash.yml
  01-input.conf:
    file: ./logstash/config/01-inputs.conf
  10-syslog.conf:
    file: ./logstash/config/10-syslog.conf
  11-pfsense.conf:
    file: ./logstash/config/11-pfsense.conf
  30-outputs.conf:
    file: ./logstash/config/30-outputs.conf
  pfsense_2_4_2.grok:
    file: ./logstash/pipeline/pfsense_2_4_2.grok
  logstash_pipeline:
    file: ./logstash/pipeline/logstash.conf
#kibana config
  kibana_config:
    file: ./kibana/config/kibana.yml
    

networks:
  elk:
    driver: overlay
