version: '3.7'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.2
    ports:
      - "9200:9200"
      - "9300:9300"
    container_name: elasticsearch
#    configs:
#      - source: elastic_config
#        target: /usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - node.name=esma01
#     - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
#     - cluster.routing.allocation.enable: all
      - cluster.name=docker-cluster
      - discovery.zen.minimum_master_nodes=2
      ######node tipe####
#      - "node.master=true"
#      - "node.data=false"
#      - "node.ingest=false"
#      - "cluster.remote.connect=false"
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 1
    volumes:
#      - /data/elk:/usr/share/elasticsearch/data
      - /etc/localtime:/etc/localtime
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    cap_add:
      - ALL
    privileged: true
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  elasticsearch_master02:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.2
    container_name: elasticsearch_master02
#    configs:
#      - source: elastic_config
#        target: /usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - node.name=esma02
#     - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
#     - cluster.routing.allocation.enable: all
      - cluster.name=docker-cluster
      - discovery.zen.minimum_master_nodes=3
      ######node tipe####
      - "node.master=true"
      - "node.data=false"
#      - "node.ingest=false"
#      - "cluster.remote.connect=false"
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 1
    volumes:
#      - /data/elk:/usr/share/elasticsearch/data
      - /etc/localtime:/etc/localtime
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    cap_add:
      - ALL
    privileged: true
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  elasticsearch_master03:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.2
    container_name: elasticsearch_master03
    environment:
      - node.name=esma03
      - cluster.name=docker-cluster
 #     - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
      ######node tipe####
      - "node.master=true"
      - "node.data=false"
#      - "node.ingest=false"
#      - "cluster.remote.connect=false"
    networks:
      - elk
    volumes:
      - elastic_data04:/usr/share/elasticsearch/data
      - /etc/localtime:/etc/localtime
    depends_on:
      - elasticsearch
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    cap_add:
      - ALL
    privileged: true
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s         

  elasticsearch_coord01:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.2
    container_name: elasticsearch_cord01
    environment:
      - node.name=escord01
#      - bootstrap.memory_lock=true
      - cluster.name=docker-cluster
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
      ######node tipe####
      - "node.master=false"
      - "node.data=false"
      - "node.ingest=false"
      - "cluster.remote.connect=false"
    networks:
      - elk
    volumes:
      - elastic_data02:/usr/share/elasticsearch/data
      - /etc/localtime:/etc/localtime
    depends_on:
      - elasticsearch
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    cap_add:
      - ALL
    privileged: true
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  elasticsearch_ingest01:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.2
    container_name: elasticsearch_ingest01
    environment:
      - node.name=esin01
      - cluster.name=docker-cluster
#      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"    
      - "discovery.zen.ping.unicast.hosts=elasticsearch"
      ######node tipe####
#      - "node.master=false"
      - "node.data=false"
#      - "node.ingest=true"
#      - "cluster.remote.connect=false"     
    networks:
      - elk
    volumes:
      - elastic_data03:/usr/share/elasticsearch/data
      - /etc/localtime:/etc/localtime
    depends_on:
      - elasticsearch
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    cap_add:
      - ALL
    privileged: true
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s      

  elasticsearch_data01:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.2
    container_name: elasticsearch_data01
#    configs:
#      - source: elastic_config
#        target: /usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      - node.name=esdata01
#     - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
#     - cluster.routing.allocation.enable: all
      - cluster.name=docker-cluster
#      - discovery.zen.minimum_master_nodes=1
      ######node tipe####
      - "node.master=false"
      - "node.data=true"
      - "node.ingest=false"
      - "cluster.remote.connect=false"
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - /data/elk:/usr/share/elasticsearch/data
      - /etc/localtime:/etc/localtime
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    cap_add:
      - ALL
    privileged: true
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

  logstash:
    image: docker.elastic.co/logstash/logstash:6.6.2
    ports:
      #- "5000:5000"
      #- "5000:5000/udp"
      - "514:5000/udp"
      - "514:5000"
      - "9600:9600"
    configs:
      #ogirinal
      - source: logstash_config
        target: /usr/share/logstash/config/logstash.yml
      - source: logstash_pipeline
        target: /usr/share/logstash/pipeline/logstash.conf
      - source: logstash_elasticsearch-template.json
        target: /opt/logstash/elasticsearch-template.json
      #- source: logstash_winad
      #  target: /usr/share/logstash/pipeline/winad.conf
      ###fim original
      #- source: 01-input.conf
      #  target: /etc/logstash/conf.d/01-input.conf
      #- source: 11-pfsense.conf
      #  target: /etc/logstash/conf.d/11-pfsense.conf
      #- source: 10-syslog.conf
      #  target: /etc/logstash/conf.d/10.syslog.conf
      #- source: 30-outputs.conf
      #  target: /etc/logstash/conf.d/30-outputs.conf
      #- source: pfsense.grok
      #  target: /etc/logstash/conf.d/patterns/pfsense.grok
    depends_on:
      - elasticsearch
        
    environment:
      LS_JAVA_OPTS: "-Xmx2g -Xms2g"
    networks:
      - elk
    volumes:
      - /etc/localtime:/etc/localtime
    deploy:
      mode: replicated
      replicas: 1

  kibana:
    image: docker.elastic.co/kibana/kibana:6.6.2
    ports:
      - "5601:5601"
    configs:
      - source: kibana_config
        target: /usr/share/kibana/config/kibana.yml
    volumes:
      - /etc/localtime:/etc/localtime
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - elasticsearch
    ulimits:
      nproc: 65535
      memlock:
        soft: -1
        hard: -1
    cap_add:
      - ALL
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s      

configs:
##elasticsearsh configs
  elastic_config:
    file: ./elasticsearch/config/elasticsearch.yml
#Logstash configs
  logstash_config:
    file: ./logstash/config/logstash.yml
  #01-input.conf:
  #  file: ./logstash/config/01-inputs.conf
  #10-syslog.conf:
  #  file: ./logstash/config/10-syslog.conf
  #11-pfsense.conf:
  #  file: ./logstash/config/11-pfsense.conf
  #30-outputs.conf:
  #  file: ./logstash/config/30-outputs.conf
  pfsense.grok:
    file: ./logstash/pipeline/pfsense.grok
  logstash_pipeline:
    file: ./logstash/pipeline/logstash.conf
  logstash_elasticsearch-template.json:
    file: ./logstash/pipeline/elasticsearch-template.json
  #logstash_winad:
  #  file: ./logstash/pipeline/winad.conf
#kibana config
  kibana_config:
    file: ./kibana/config/kibana.yml
    
volumes:
  elastic_data02:
  elastic_data03:
  elastic_data04:
networks:
  elk:
    driver: overlay