# vim: set relativenumber nonu shiftwidth=2 tabstop=2 softtabstop=-1 expandtab wrap:
version: '3.7'

services:
  elasticsearch-hot:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
    environment:
      - node.attr.box_type=hot
      - node.attr.size=hot
      - ilm_enabled=true
#      - bootstrap.memory_lock=true
      - node.name=elasticsearch-hot
      - cluster.name=docker-cluster
      - cluster.initial_master_nodes=elasticsearch-hot,elasticsearsh-warm,elasticsearch-cold
      - discovery.seed_hosts=elasticsearsh-warm,elasticsearch-cold
      - xpack.monitoring.collection.enabled=true
      - path.repo=/usr/share/elasticsearch/backup
      - "ES_JAVA_OPTS=-Xms800m -Xmx800m"
    networks:
      - elk
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 512M
    volumes:
      - elastic_hot:/usr/share/elasticsearch/data
      - elastic_backup:/usr/share/elasticsearch/backup
      - /etc/localtime:/etc/localtime

  elasticsearch-warm:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
    environment:
      - node.attr.box_type=warm
      - node.attr.size=warm
      - ilm_enabled=true
#      - bootstrap.memory_lock=true
      - node.name=elasticsearch-warm
      - cluster.name=docker-cluster
      - cluster.initial_master_nodes=elasticsearch-hot,elasticsearch-cold,elasticsearch-warm
      - discovery.seed_hosts=elasticsearch-hot,elasticsearch-cold
      - xpack.monitoring.collection.enabled=true
      - path.repo=/usr/share/elasticsearch/backup
      - "ES_JAVA_OPTS=-Xmx800m -Xms800m"
    networks:
      - elk
    volumes:
      - elastic_warm:/usr/share/elasticsearch/data
      - elastic_backup:/usr/share/elasticsearch/backup
      - /etc/localtime:/etc/localtime
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '2.0'
          memory: 512M

  elasticsearch-cold:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
    environment:
      - node.attr.box_type=cold
      - node.attr.size=warm
      - ilm_enabled=true
#      - cluster.routing.allocation.enable=all
#      - bootstrap.memory_lock=true
      - node.name=elasticsearch-cold
      - cluster.initial_master_nodes=elasticsearch
      - cluster.name=docker-cluster
      - cluster.initial_master_nodes=elasticsearch-hot,elasticsearch-cold,elasticsearch-warm
      - discovery.seed_hosts=elasticsearch-hot,elasticsearch-cold
      - xpack.monitoring.collection.enabled=true
      - path.repo=/usr/share/elasticsearch/backup
      - "ES_JAVA_OPTS=-Xmx800m -Xms800m"
    networks:
      - elk
    volumes:
      - elastic_cold:/usr/share/elasticsearch/data
      - elastic_backup:/usr/share/elasticsearch/backup
      - /etc/localtime:/etc/localtime
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '2.0'
          memory: 512M

  logstash:
    image: docker.elastic.co/logstash/logstash:7.9.0
    configs:
      - source: logstash_pipeline
        target: /usr/share/logstash/pipeline/logstash.conf
    ports:
      - 514:514/udp
      - 514:514
    environment:
      - "LS_JAVA_OPTS=-Xmx512m -Xms512m"
      - xpack.monitoring.enabled=true
      - monitoring.enabled=false
    networks:
      - elk
    volumes:
      - /etc/localtime:/etc/localtime
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '1.0'
          memory: 800M

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.0
    depends_on:
      - elasticsearch-hot
      - elasticsearch-warm
      - elasticsearch-cold
    ports:
      - "5601:5601"
    configs:
      - source: kibana_config
        target: /usr/share/kibana/config/kibana.yml
    volumes:
      - /etc/localtime:/etc/localtime
      - kibana_data:/usr/share/kibana/config
    networks:
      - elk
    environment:
      - elasticsearch.url=http://elasticsearch-hot:9200,http://elasticsearch-warm:9200,http://elasticsearch-cold:9200
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
#  filebeat:
#    image: docker.elastic.co/beats/filebeat:7.9.0
#    volumes:
#      - filebeat_data:/usr/share/filebeat/data
#    configs:
#      - source: filebeat_config
#        target: /usr/share/filebeat/config/filebeat.yml

configs:
  logstash_pipeline:
    file: ./logstash/pipeline/logstash.conf
  kibana_config:
    file: ./kibana/config/kibana.yml
#  filebeat_config:
#    file: ./filebeat/config/filebeat.yml

volumes:
  kibana_data:
    driver_opts:
      o: bind
      type: none
      device: /data/elk/kibana
  elastic_hot:
    driver_opts:
      o: bind
      type: none
      device: /data/elk/elasticsearch/hot
  elastic_warm:
    driver_opts:
      o: bind
      type: none
      device: /data/elk/elasticsearch/warm
  elastic_cold:
    driver_opts:
      o: bind
      type: none
      device: /data/elk/elasticsearch/cold
  elastic_backup:
    driver_opts:
      o: bind
      type: none
      device: /data/elk/elasticsearch/backup
  filebeat_data:
    driver_opts:
      o: bind
      type: none
      device: /data/elk/filebeat

networks:
  elk:
    driver: overlay
