version: '3.3'

services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1
    ports:
      - "9200:9200"
      - "9300:9300"
    #configs:
    #  - source: elastic_config
    #    target: /usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      cluster.name: docker-cluster
      ES_JAVA_OPTS: "-Xmx16g -Xms16g"
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 1
    volumes:
      - /data/elk:/usr/share/elasticsearch/data
      - /etc/localtime:/etc/localtime

  elasticsearch2:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1
    environment:
      cluster.name: docker-cluster
      ES_JAVA_OPTS: "-Xmx2g -Xms2g"
      discovery.zen.ping.unicast.hosts: elasticsearch
    networks:
      - elk
    volumes:
      - elastic_data02:/usr/share/elasticsearch/data
      - /etc/localtime:/etc/localtime

  logstash:
    image: docker.elastic.co/logstash/logstash:6.6.1
    ports:
      - "5000:5000"
      - "514:5000/udp"
      - "514:5000"
      - "9600:9600"
    configs:
      #ogirinal
      - source: logstash_config
        target: /usr/share/logstash/config/logstash.yml
      - source: logstash_pipeline
        target: /usr/share/logstash/pipeline/logstash.conf
      - source: logstash_elasticsearch-template.json
        target: /opt/logstash/elasticsearch-template.json
      - source: pfsense.grok
        target: /etc/logstash/conf.d/patterns/pfsense.grok
        
    environment:
      LS_JAVA_OPTS: "-Xmx16g -Xms16g"
    networks:
      - elk
    volumes:
      - /etc/localtime:/etc/localtime
    deploy:
      mode: replicated
      replicas: 1

  kibana:
    image: docker.elastic.co/kibana/kibana:6.6.1
    ports:
      - "5601:5601"
    configs:
      - source: kibana_config
        target: /usr/share/kibana/config/kibana.yml
    volumes:
      - /etc/localtime:/etc/localtime
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 1

configs:
#Logstash configs
  logstash_config:
    file: ./logstash/config/logstash.yml
  pfsense.grok:
    file: ./logstash/pipeline/pfsense.grok
  logstash_pipeline:
    file: ./logstash/pipeline/logstash.conf
  logstash_elasticsearch-template.json:
    file: ./logstash/pipeline/elasticsearch-template.json
#kibana config
  kibana_config:
    file: ./kibana/config/kibana.yml

volumes:
  elastic_data02:

networks:
  elk:
    driver: overlay
