filebeat.config.inputs:
  enabled: true
  filebeat.modules:
    - module: panw
      panos:
        var.syslog_host: 0.0.0.0

output.elasticsearch:
  hosts: '${ELASTICSEARCH_HOSTS:elasticsearch:9200}'
